safe: true
markdown: kramdown
pygments: true
permalink: /:title.html
relative_permalinks: false

default_theme: ribbon
default_width: 792
default_lang: en
default_body_class: list

author:
    name: Florian Gilcher
    # url:  http://example.com/
    company:
        name: asquera GmbH
        # url:  http://example.com/

fork_url: https://github.com/skade/elasticsearch-introduction
progress: true
line_numbers: true

kramdown:
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class